webtalk_init -webtalk_dir D:/Digital_Circuit/Exercise/Exercise.sim/sim_1/behav/xsim/xsim.dir/tb_Matrix_Multiplication_AGU_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Dec 17 15:25:05 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7955c207-5f20-4b8b-93a9-b4c7b11e5d6c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "30d88744e1c647c289c9e5223a4b56cf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "154" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-14900HX" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2419 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10035 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8944_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2638912231 -regid "" -xml D:/Digital_Circuit/Exercise/Exercise.sim/sim_1/behav/xsim/xsim.dir/tb_Matrix_Multiplication_AGU_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Digital_Circuit/Exercise/Exercise.sim/sim_1/behav/xsim/xsim.dir/tb_Matrix_Multiplication_AGU_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Digital_Circuit/Exercise/Exercise.sim/sim_1/behav/xsim/xsim.dir/tb_Matrix_Multiplication_AGU_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
